WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 500

BOARD_ROWS = 25
BOARD_COLS = 50
FLAG_IMG = "flag.png"
FLAG_WIDTH = 60
FLAG_HEIGHT = 80
player_x, player_y = 0 , 0
MINE_HEIGHT = 40
MINE_WIDTH = 120
TILE_SIZE = 20
BOARD_ROWS = 25
BOARD_SOLS = 50

SOLDIER_IMG = "soldier.png"
SOLDIER_BODY_HEIGHT = 80
SOLDIER_BODY_WIDTH = 80
SOLDIER_LEGS_HEIGHT = 1
SOLDIER_LEGS_WIDTH = 2
player_size = 100


GRASS_IMG = "grass.png"
GRASS_HEIGHT = 50
GRASS_WIDTH = 50
BACKGROUND_COLOR = (254, 252, 252)
DARK_GREEN = (0, 100, 0)
BLACK = (0, 0, 0)
red = (255, 0, 0)

FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

WELCOME_MESSAGE = "Welcome to The Flag game. Have Fun!"
WELCOME_FONT_SIZE = int(30)
WELCOME_COLOR = (255, 255, 255)
WELCOME_LOCATION = (20, 20)

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3